Array - Iteration,indexing,append/insert, remove/pop

Advance : L/R shift, Rotating, Circular


In [ ]:
import numpy as np

b = np.array([1,2,3], dtype = int)
print(b)
#for 1 D is len

[1 2 3]


In [ ]:
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

In [ ]:
a1 =  np.array([1,2,3], dtype = int)
a2 =  np.array([3,5,6], dtype = int)
print(a1+a2)
size1,size2 = len(a1),len(a2)
c_size = size1 + size2
c1 = np.array([0]*c_size)
print(f"size1 : {size1}\nsize2 : {size2}")
print(f"a1 : {a1}\na2 : {a2}")
print(c1)
print()

i = j = k = 0
while i < size1 and j < size2:
    if a1[i] < a2[j]:
      c1[k] = a1[i]
      i += 1
    else:
      c1[k] = a2[j]
      j += 1
    k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")
print()

#print(c1) [1 2 2 3 0 0] not all a2 elem found
while i < size1:
  c1[k] = a1[i]
  i += 1
  k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")
print()

while j < size2:  #j=1, size2=3
  c1[k] = a2[j]
  print(a2[j],end="->\n")
  j += 1
  k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")

[4 7 9]
size1 : 3
size2 : 3
a1 : [1 2 3]
a2 : [3 5 6]
[0 0 0 0 0 0]

[1 2 3 3 0 0]
i : 3, j : 1, k : 4

[1 2 3 3 0 0]
i : 3, j : 1, k : 4

5->
6->
[1 2 3 3 5 6]
i : 3, j : 3, k : 6


In [ ]:
a1 =  np.array([2,5,6], dtype = int)
a2 =  np.array([1,2,3], dtype = int)
print(a1+a2)
size1,size2 = len(a1),len(a2)
c_size = size1 + size2
c1 = np.array([0]*c_size)
print(f"size1 : {size1}\nsize2 : {size2}")
print(f"a1 : {a1}\na2 : {a2}")
print(c1)
i = j = k = 0
while i < size1 and j < size2:
    if a1[i] < a2[j]:
      c1[k] = a1[i]
      i += 1
    else:
      c1[k] = a2[j]
      j += 1
    k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")
#print(c1) [1 2 2 3 0 0] not all a2 elem found
while i < size1: # i = 0, coz only a1[0]=2 has been taken
  c1[k] = a1[i]
  i += 1          # i = 1+1 =2,  i = 2+1 =3
  i += 1
  k += 1
print(c1) #[1 2 2 3 5 6]
print(f"i : {i}, j : {j}, k : {k}")
while j < size2:
  c1[k] = a2[j]
  j += 1
  k += 1
print(c1)  #[1 2 2 3 5 6]
print(f"i : {i}, j : {j}, k : {k}")

[3 7 9]
size1 : 3
size2 : 3
a1 : [2 5 6]
a2 : [1 2 3]
[0 0 0 0 0 0]
[1 2 2 3 0 0]
i : 1, j : 3, k : 4
[1 2 2 3 5 0]
i : 3, j : 3, k : 5
[1 2 2 3 5 0]
i : 3, j : 3, k : 5


In [ ]:
a1 =  np.array([1,2,3], dtype = int)
a2 =  np.array([4,5,6], dtype = int)
print(a1+a2)
size1,size2 = len(a1),len(a2)
c_size = size1 + size2
c1 = np.array([0]*c_size)
print(f"size1 : {size1}\nsize2 : {size2}")
print(f"a1 : {a1}\na2 : {a2}")
print(c1)
i = j = k = 0
while i < size1 and j < size2:
    if a1[i] < a2[j]:
      c1[k] = a1[i]
      i += 1
    else:
      c1[k] = a2[j]
      j += 1
    k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")
#print(c1) [1 2 3 0 0 0] not all a2 elem found
while i < size1:
  c1[k] = a1[i]
  i += 1
  k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")
while j < size2:
  c1[k] = a2[j]
  j += 1
  k += 1
print(c1)
print(f"i : {i}, j : {j}, k : {k}")

[5 7 9]
size1 : 3
size2 : 3
a1 : [1 2 3]
a2 : [4 5 6]
[0 0 0 0 0 0]
[1 2 3 0 0 0]
[1 2 3 0 0 0]
[1 2 3 4 5 6]


In [ ]:
import numpy as np
import unittest  # Assuming unittest.output_test() is defined elsewhere

def mergeSortedArray(arr1, arr2):
    size1, size2 = len(arr1), len(arr2)
    merged_size = size1 + size2
    merged_arr = np.array([0] * merged_size)  # Initialize merged array

    i = j = k = 0

    # Merge two sorted arrays into merged_arr
    while i < size1 and j < size2:
        if arr1[i] <= arr2[j]:
            merged_arr[k] = arr1[i]
            i += 1
        else:
            merged_arr[k] = arr2[j]
            j += 1
        k += 1

    # Copy remaining elements from arr1
    while i < size1:
        merged_arr[k] = arr1[i]
        i += 1
        k += 1

    # Copy remaining elements from arr2
    while j < size2:
        merged_arr[k] = arr2[j]
        j += 1
        k += 1

    return merged_arr  # Return the manually merged sorted array

# Driver Code
a1 = np.array([1, 2, 3])
print(f'Sorted Array 1: {a1}')
a2 = np.array([2, 5, 6])
print(f'Sorted Array 2: {a2}')
returned_value = mergeSortedArray(a1, a2)
print(f'Merged Sorted Array: {returned_value}\n')  # Expected: [1, 2, 2, 3, 5, 6]
unittest.output_test(returned_value, np.array([1, 2, 2, 3, 5, 6]))

print('\n==================================\n')

a3 = np.array([1, 3, 5, 11])
print(f'Sorted Array 3: {a3}')
a4 = np.array([2, 7, 8])
print(f'Sorted Array 4: {a4}')
returned_value = mergeSortedArray(a3, a4)
print(f'Merged Sorted Array: {returned_value}\n')  # Expected: [1, 2, 3, 5, 7, 8, 11]
unittest.output_test(returned_value, np.array([1, 2, 3, 5, 7, 8, 11]))


Sorted Array 1: [1 2 3]
Sorted Array 2: [2 5 6]
Merged Sorted Array: [1 2 2 3 5 6]



AttributeError: module 'unittest' has no attribute 'output_test'

In [ ]:
#Assignment-02

#1. Check Even or Odd: Write a program to check if a given number is even or odd.

var = input("Enter a number : ")
if var.lstrip('-').isnumeric() or var.isnumeric():
  var = int(var)
  if var%2 == 0:
    print(f"{var} is EVEN!")
  else:
    print(f"{var} is ODD!")
else:
  print(f"{var} is an invalid input!")

Enter a number : -12
-12 is EVEN!


In [ ]:
# 2. Positive, Negative, or Zero: Determine if a number is positive, negative, or zero.

var = input("Enter a number : ")
if var.lstrip('-').isnumeric() or var.isnumeric():
  var = int(var)
  if var < 0:
    print(f"{var} is a Negative number!")
  elif var > 0:
    print(f"{var} is Positive number!")
  else :
    print("The entered number is ZERO!")
else:
  print(f"{var} is an invalid input!")

Enter a number : l
l is an invalid input!


In [ ]:
# 3. Vowel or Consonant: Write a program to check whether a character is a vowel or consonant.

char = input("Enter a single character: ").lower()

if len(char) == 1 and char.isalpha():
    if char in "aeiou":
        print(f"{char} is a VOWEL!")
    else:
        print(f"{char} is a CONSONANT!")
else:
    print("Invalid input! Please enter a single alphabet character.")

Enter a single character: 1
Invalid input! Please enter a single alphabet character.


In [ ]:
# 4. Leap Year: Check if a given year is a leap year or not.

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a Leap Year!")
else:
    print(f"{year} is NOT a Leap Year.")

Enter a year: 2024
2024 is a Leap Year!


In [ ]:
#5. Grade Evaluator: Given a score, print the grade (A, B, C, D, or F) based on predefined ranges.

score = input("Enter the score: ")

if score.isnumeric():
  score = float(score)
  if 90 <= score <= 100:
      print("Grade: A")
  elif 80 <= score < 90:
      print("Grade: B")
  elif 70 <= score < 80:
      print("Grade: C")
  elif 60 <= score < 70:
      print("Grade: D")
  else:
      print("Grade: F")
else:
    print("Invalid score! Please enter a number between 0 and 100.")

Enter the score: 50
Grade: F


In [ ]:
#6. Check Divisibility: Check if a number is divisible by both 5 and 11 or not.

num = input("Enter a number: ")

if num.isnumeric():
  num = int(num)
  if num % 5 == 0 and num % 11 == 0:
      print(f"{num} is divisible by both 5 and 11!")
  else:
      print(f"{num} is NOT divisible by both 5 and 11.")
else:
  print("Invalid number! Please enter a valid number")

Enter a number: l
Invalid number! Please enter a valid number


In [ ]:
#7. Max of Three Numbers: Find the largest of three numbers.

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))


max_number = max(num1, num2, num3)
print(f"The largest number is: {max_number}")

Enter first number: 13
Enter second number: 25
Enter third number: 7
The largest number is: 25.0


In [ ]:
#8. Traffic Light: Given the color of a traffic light (red, yellow, green), print the action (stop, ready, go).

color = input("Enter the traffic light color (red, yellow, green): ").strip().lower()

if color == "red":
    print("STOP!")
elif color == "yellow":
    print("GET READY!")
elif color == "green":
    print("GO!")
else:
    print("Invalid color! Please enter red, yellow, or green.")

Enter the traffic light color (red, yellow, green): F
Invalid color! Please enter red, yellow, or green.


In [ ]:
#Increasing triangle

n = 5
for i in range(n):
  for j in range(i+1):
    print('*',end=' ')
  print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
#decreasing triangle

n = 5
for i in range(n):
  for j in range(i,n):
    print('*',end=' ')
  print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
#Increasing space + Decreasing star

n = 5
for i in range(n):
  for j in range(i+1):
    print(' ',end=' ')
  for j in range(i,n):
    print('*',end=' ')
  print()

  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [ ]:
#Decreasing space + Increasing star
n = 5
for i in range(n):
  for j in range(i,n):
    print(' ',end=' ')
  for j in range(i+1):
    print('*',end=' ')
  print()

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [ ]:
import numpy as np

# Define the Node class
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None  # Pointer to the next node

# Function to create a linked list from an array
def createList(arr):
    if len(arr) == 0:
        return None  # If the array is empty, return None

    head = Node(arr[0])  # Create the first node as head
    current = head

    for value in arr[1:]:
        newNode = Node(value)
        current.next = newNode  # Link the new node
        current = newNode  # Move to the new node

    return head  # Return the head of the linked list

# Function to print the linked list
def printLL(head):
    if head is None:
        print("Linked List is empty")
        return

    current = head
    while current is not None:
        print(current.elem, end=" -> ")
        current = current.next
    print("None")

# Function to get the last node (tail)
def get_tail(head):
    if head is None:
        return None

    current = head
    while current.next is not None:
        current = current.next
    return current  # Return the last node

# Function to append a node at the end of the linked list
def appendLL(head, data):
    newNode = Node(data)

    if head is None:  # If list is empty, return newNode as head
        return newNode

    tail = get_tail(head)  # Find the last node
    tail.next = newNode  # Link the new node at the end

    return head  # Head remains unchanged but returned for safety

# Function to check if an element exists in the linked list
def contains(head, target):
    current_node = head
    while current_node is not None:
        if current_node.elem == target:
            return True
        current_node = current_node.next
    return False  # Element not found

# Create a linked list from an array
arr = np.array([10, 20, 30, 40, 50])
head3 = createList(arr)

# Print the linked list
print("Linked List:")
printLL(head3)

# Searching for elements
target = 40
exists = contains(head3, target)
print(f"Contains {target}: {exists}")

target = 60
exists = contains(head3, target)
print(f"Contains {target}: {exists}")

# Handling an empty linked list case
empty_head = None
print("\nTesting empty linked list:")
printLL(empty_head)

target = 40
# exists = contains(empty_head, target)
# print(f"Contains {target}: {exists}")  # Expected output: False

# # Append elements to an empty linked list
# empty_head = appendLL(empty_head, 100)
# print("\nAfter appending to empty linked list:")
# printLL(empty_head)


Linked List:
10 -> 20 -> 30 -> 40 -> 50 -> None
Contains 40: True
Contains 60: False

Testing empty linked list:
Linked List is empty
